//
// Generated file, do not edit! Created by nedtool 4.6 from applications/trafficlightapp/Ciao.msg.
//

#ifndef _CIAO_M_H_
#define _CIAO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



/**
 * Class generated from <tt>applications/trafficlightapp/Ciao.msg:1</tt> by nedtool.
 * <pre>
 * packet Ciao
 * {
 *     int ID;
 *     long data;
 * 
 * }
 * </pre>
 */
class INET_API Ciao : public ::cPacket
{
  protected:
    int ID_var;
    long data_var;

  private:
    void copy(const Ciao& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ciao&);

  public:
    Ciao(const char *name=NULL, int kind=0);
    Ciao(const Ciao& other);
    virtual ~Ciao();
    Ciao& operator=(const Ciao& other);
    virtual Ciao *dup() const {return new Ciao(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getID() const;
    virtual void setID(int ID);
    virtual long getData() const;
    virtual void setData(long data);
};

inline void doPacking(cCommBuffer *b, Ciao& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Ciao& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CIAO_M_H_

