//
// Generated file, do not edit! Created by nedtool 4.6 from networklayer/manetrouting/aodv-uu/aodv_msg_struct.msg.
//

#ifndef _AODV_MSG_STRUCT_M_H_
#define _AODV_MSG_STRUCT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



// cplusplus {{
#include "aodv_msg_struct.h"
// }}


#endif // ifndef _AODV_MSG_STRUCT_M_H_

